chore: replace tslint with eslint
mgechev/injection-js pull request #55
Opened 2022-04-18 10:00 UTC by vthinkxie

close #52

2022-04-19 02:26 UTC, mgechev commented on lib/facade/errors.ts
> +import { DebugContext } from "./lang";
Let's go with single quotes.

2022-04-19 02:26 UTC, mgechev requested changes
Let's go with single quotes. We can merge after.

2022-04-19 02:37 UTC, vthinkxie commented
> Let's go with single quotes. We can merge after.

done

2022-04-21 19:05 UTC, mgechev approved these changes

2022-04-21 19:06 UTC, merged